name: CI
on: [pull_request]

jobs:
  build-linux:
    strategy:
      matrix:
        rustc: ["1.56.0", "stable"]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxrandr-dev xorg-dev libsdl2-dev
      - uses: actions/checkout@v2
      - name: Build
        run: |
          rustup default ${{ matrix.rustc }}
          cargo build
          cargo test

  build-windows:
    strategy:
      matrix:
        rustc: ["1.56.0"]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          rustup default ${{ matrix.rustc }}
          cargo build
          cargo test

  build-macosx:
    strategy:
      matrix:
        rustc: ["1.56.0"]
    runs-on: macOS-latest
    steps:
      - name: Install dependencies
        run: brew install SDL2
      - uses: actions/checkout@v2
      - name: Build
        run: |
          rustup default ${{ matrix.rustc }}
          cargo build
          cargo test

  # build-wasm:
  #   strategy:
  #     matrix:
  #       rustc: ["1.56.0"]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install rustup WASM toolchain
  #       run: |
  #         rustup default ${{ matrix.rustc }}
  #         rustup target install wasm32-unknown-unknown
  #     - uses: actions/checkout@v2
  #     - name: Build
  #       run: |
  #         cd $GITHUB_WORKSPACE/luminance-webgl
  #         cargo build
  #         cd $GITHUB_WORKSPACE/luminance-web-sys
  #         cargo build
  #         cd $GITHUB_WORKSPACE/examples/web
  #         yarn install
  #         yarn build

  # functional-tests-desktop:
  #   strategy:
  #     matrix:
  #       rustc: ["1.56.0"]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y libxrandr-dev xorg-dev libsdl2-dev
  #     - uses: actions/checkout@v2
  #     - name: Functional testing
  #       run: |
  #         rustup default ${{ matrix.rustc }}
  #         cd examples/desktop
  #         cargo check --features funtest,funtest-gl33-f64-uniform
  #
  # functional-tests-web:
  #   strategy:
  #     matrix:
  #       rustc: ["1.56.0"]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install rustup WASM toolchain
  #       run: |
  #         rustup default ${{ matrix.rustc }}
  #         rustup target install wasm32-unknown-unknown
  #     - uses: actions/checkout@v2
  #     - name: Functional testing
  #       run: |
  #         cd examples/web
  #         cargo check --features funtest

  quality:
    strategy:
      matrix:
        rustc: ["1.56.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          rustup default ${{ matrix.rustc }}
          rustup component add rustfmt
          cargo install --force cargo-sync-readme
      - name: cargo sync-readme luminance
        run: |
          cd $GITHUB_WORKSPACE/luminance
          cargo sync-readme -c
      - name: cargo sync-readme luminance-derive
        run: |
          cd $GITHUB_WORKSPACE/luminance-derive
          cargo sync-readme -c
      - name: cargo sync-readme luminance-front
        run: |
          cd $GITHUB_WORKSPACE/luminance-front
          cargo sync-readme -c
      - name: cargo sync-readme luminance-gl
        run: |
          cd $GITHUB_WORKSPACE/luminance-gl
          cargo sync-readme -c
      - name: cargo sync-readme luminance-glfw
        run: |
          cd $GITHUB_WORKSPACE/luminance-glfw
          cargo sync-readme -c
      - name: cargo sync-readme luminance-glutin
        run: |
          cd $GITHUB_WORKSPACE/luminance-glutin
          cargo sync-readme -c
      - name: cargo sync-readme luminance-sdl2
        run: |
          cd $GITHUB_WORKSPACE/luminance-sdl2
          cargo sync-readme -c
      - name: cargo sync-readme luminance-std140
        run: |
          cd $GITHUB_WORKSPACE/luminance-std140
          cargo sync-readme -c
      - name: cargo sync-readme luminance-web-sys
        run: |
          cd $GITHUB_WORKSPACE/luminance-web-sys
          cargo sync-readme -c
      - name: cargo sync-readme luminance-webgl
        run: |
          cd $GITHUB_WORKSPACE/luminance-webgl
          cargo sync-readme -c
      - name: rustfmt
        run: |
          cargo fmt -- --check
